<?php

namespace Database\Seeders;
use Dotenv\Util\Str;
use Illuminate\Database\Seeder;

class CoursesEnTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('courses_en')->delete();

        \DB::table('courses_en')->insert(array (
            0 =>
            array (
                'unique_id' => '58',
                'language' => NULL,
                'program_type' => NULL,
                'study_mode' => NULL,
                'school_id' => NULL,
                'branch' => NULL,
                'currency' => 'USD',
                'program_name' => \Str::random(10),
                'program_level' => NULL,
                'lessons_per_week' => NULL,
                'hours_per_week' => NULL,
                'study_time' => NULL,
                'every_day' => '["Monday"]',
                'about_program' => NULL,
                'created_at' => '2021-04-09 16:21:12',
                'updated_at' => '2021-04-09 16:21:12',
            ),
            1 =>
            array (
                'unique_id' => '89',
                'language' => NULL,
                'program_type' => '["New program"]',
                'study_mode' => '["Online"]',
                'school_id' => '1614258254',
                'branch' => '["fddd"]',
                'currency' => 'CAD',
                'program_name' => \Str::random(10),
                'program_level' => NULL,
                'lessons_per_week' => 'Et sed labore non et',
                'hours_per_week' => 'Cupidatat delectus',
                'study_time' => '["Morning","Afternoon","Evening"]',
                'every_day' => '["Monday"]',
                'about_program' => 'Quas occaecat molest',
                'created_at' => '2021-04-08 23:46:15',
                'updated_at' => '2021-04-08 23:46:15',
            ),
            2 =>
            array (
                'unique_id' => '131',
                'language' => '["English"]',
                'program_type' => '["New program"]',
                'study_mode' => '["Online"]',
                'school_id' => '1614169810',
                'branch' => '["Branch Name"]',
                'currency' => 'USD',
                'program_name' => \Str::random(10),
                'program_level' => NULL,
                'lessons_per_week' => 'Fugiat velit eaque',
                'hours_per_week' => 'Soluta eum sed dolor',
                'study_time' => '["Morning"]',
                'every_day' => '["Monday"]',
                'about_program' => 'Ut quis est neque ul',
                'created_at' => '2021-04-08 07:30:33',
                'updated_at' => '2021-04-08 07:30:33',
            ),
            3 =>
            array (
                'unique_id' => '141',
                'language' => NULL,
                'program_type' => NULL,
                'study_mode' => NULL,
                'school_id' => NULL,
                'branch' => NULL,
                'currency' => NULL,
                'program_name' => \Str::random(10),
                'program_level' => NULL,
                'lessons_per_week' => NULL,
                'hours_per_week' => NULL,
                'study_time' => NULL,
                'every_day' => '["Monday"]',
                'about_program' => NULL,
                'created_at' => '2021-04-08 08:01:04',
                'updated_at' => '2021-04-08 08:01:04',
            ),
            4 =>
            array (
                'unique_id' => '156',
                'language' => '"English"',
                'program_type' => '["New program"]',
                'study_mode' => '["Offline"]',
                'school_id' => '1614169810',
                'branch' => '["Branch Name"]',
                'currency' => 'USD',
                'program_name' => \Str::random(10),
                'program_level' => NULL,
                'lessons_per_week' => '30',
                'hours_per_week' => '22.5',
                'study_time' => '["Morning"]',
                'every_day' => '["Monday"]',
                'about_program' => 'test',
                'created_at' => '2021-04-09 15:04:48',
                'updated_at' => '2021-04-09 15:04:48',
            ),
            5 =>
            array (
                'unique_id' => '340',
                'language' => '"English"',
                'program_type' => '["New program"]',
                'study_mode' => '["Online","Offline"]',
                'school_id' => '176',
                'branch' => '["center"]',
                'currency' => 'GBP',
                'program_name' => \Str::random(10),
                'program_level' => NULL,
                'lessons_per_week' => '12',
                'hours_per_week' => '12',
                'study_time' => '["Morning"]',
                'every_day' => '["Monday"]',
                'about_program' => 'About program',
                'created_at' => '2021-04-11 20:30:09',
                'updated_at' => '2021-04-11 20:30:09',
            ),
            6 =>
            array (
                'unique_id' => '365',
                'language' => NULL,
                'program_type' => '["New program"]',
                'study_mode' => '["Online","Offline"]',
                'school_id' => '176',
                'branch' => '["center"]',
                'currency' => 'CAD',
                'program_name' => \Str::random(10),
                'program_level' => NULL,
                'lessons_per_week' => '100',
                'hours_per_week' => '10',
                'study_time' => '["Morning"]',
                'every_day' => '["Monday"]',
                'about_program' => 'About program',
                'created_at' => '2021-04-11 20:22:36',
                'updated_at' => '2021-04-11 20:22:36',
            ),
            7 =>
            array (
                'unique_id' => '436',
                'language' => '"English"',
                'program_type' => '["General English"]',
                'study_mode' => '["Offline"]',
                'school_id' => '1614169810',
                'branch' => '["Branch Name"]',
                'currency' => 'GBP',
                'program_name' => \Str::random(10),
                'program_level' => NULL,
                'lessons_per_week' => '30',
                'hours_per_week' => '22.5',
                'study_time' => '["Morning"]',
                'every_day' => '["Monday"]',
                'about_program' => 'test',
                'created_at' => '2021-04-11 20:31:21',
                'updated_at' => '2021-04-11 20:31:21',
            ),
            8 =>
            array (
                'unique_id' => '478',
                'language' => '"English"',
                'program_type' => '["intensive"]',
                'study_mode' => '["Offline"]',
                'school_id' => '176',
                'branch' => '["center"]',
                'currency' => 'USD',
                'program_name' => \Str::random(10),
                'program_level' => 'test',
                'lessons_per_week' => '300',
                'hours_per_week' => '20',
                'study_time' => '["Morning"]',
                'every_day' => '["Monday"]',
                'about_program' => 'TEST',
                'created_at' => '2021-04-11 21:03:45',
                'updated_at' => '2021-04-11 21:03:45',
            ),
            9 =>
            array (
                'unique_id' => '609',
                'language' => NULL,
                'program_type' => NULL,
                'study_mode' => NULL,
                'school_id' => NULL,
                'branch' => NULL,
                'currency' => NULL,
                'program_name' => \Str::random(10),
                'program_level' => NULL,
                'lessons_per_week' => NULL,
                'hours_per_week' => NULL,
                'study_time' => NULL,
                'every_day' => '["Monday"]',
                'about_program' => NULL,
                'created_at' => '2021-04-08 07:32:49',
                'updated_at' => '2021-04-08 07:32:49',
            ),
            10 =>
            array (
                'unique_id' => '627',
                'language' => '"English"',
                'program_type' => '["intensive"]',
                'study_mode' => '["Offline"]',
                'school_id' => '176',
                'branch' => '["center"]',
                'currency' => 'USD',
                'program_name' => \Str::random(10),
                'program_level' => 'A1',
                'lessons_per_week' => '30',
                'hours_per_week' => '22.5',
                'study_time' => '["Morning"]',
                'every_day' => '["Monday"]',
                'about_program' => 'ttttttttttttttt',
                'created_at' => '2021-04-12 12:53:11',
                'updated_at' => '2021-04-12 12:53:11',
            ),
            11 =>
            array (
                'unique_id' => '655',
                'language' => '"English"',
                'program_type' => '["General English"]',
                'study_mode' => '["Offline"]',
                'school_id' => '176',
                'branch' => '["center"]',
                'currency' => 'GBP',
                'program_name' => \Str::random(10),
                'program_level' => NULL,
                'lessons_per_week' => '20',
                'hours_per_week' => '15',
                'study_time' => '["Morning"]',
                'every_day' => '["Monday"]',
                'about_program' => 'efsdfsd',
                'created_at' => '2021-04-11 17:33:56',
                'updated_at' => '2021-04-11 17:33:56',
            ),
            12 =>
            array (
                'unique_id' => '660',
                'language' => NULL,
                'program_type' => '["New program"]',
                'study_mode' => '["Online"]',
                'school_id' => '1614169810',
                'branch' => '["Branch Name"]',
                'currency' => 'AUS',
                'program_name' => \Str::random(10),
                'program_level' => NULL,
                'lessons_per_week' => 'Nulla incididunt qua',
                'hours_per_week' => 'Tempor aliquid nisi',
                'study_time' => '["Morning"]',
                'every_day' => '["Monday"]',
                'about_program' => 'Sed consequatur ut',
                'created_at' => '2021-04-09 10:57:02',
                'updated_at' => '2021-04-09 10:57:02',
            ),
            13 =>
            array (
                'unique_id' => '664',
                'language' => '"English"',
                'program_type' => '["473"]',
                'study_mode' => '["Offline"]',
                'school_id' => '176',
                'branch' => '["center"]',
                'currency' => 'GBP',
                'program_name' => \Str::random(10),
                'program_level' => 'A1',
                'lessons_per_week' => '30',
                'hours_per_week' => '20',
                'study_time' => '["Morning"]',
                'every_day' => '["Monday"]',
                'about_program' => 'erererererere',
                'created_at' => '2021-04-11 20:54:50',
                'updated_at' => '2021-04-11 20:54:50',
            ),
            14 =>
            array (
                'unique_id' => '778',
                'language' => '"English"',
                'program_type' => '["General English"]',
                'study_mode' => '["Offline"]',
                'school_id' => '176',
                'branch' => '["center"]',
                'currency' => 'GBP',
                'program_name' => \Str::random(10),
                'program_level' => NULL,
                'lessons_per_week' => '35',
                'hours_per_week' => '20',
                'study_time' => '["Morning"]',
                'every_day' => '["Monday"]',
                'about_program' => 'test',
                'created_at' => '2021-04-11 18:17:34',
                'updated_at' => '2021-04-11 18:17:34',
            ),
            15 =>
            array (
                'unique_id' => '837',
                'language' => NULL,
                'program_type' => NULL,
                'study_mode' => NULL,
                'school_id' => NULL,
                'branch' => NULL,
                'currency' => 'USD',
                'program_name' => \Str::random(10),
                'program_level' => NULL,
                'lessons_per_week' => NULL,
                'hours_per_week' => NULL,
                'study_time' => NULL,
                'every_day' => '["Monday"]',
                'about_program' => NULL,
                'created_at' => '2021-04-10 04:00:15',
                'updated_at' => '2021-04-10 04:00:15',
            ),
            16 =>
            array (
                'unique_id' => '845',
                'language' => '"English"',
                'program_type' => '["New program","General English","intensive"]',
                'study_mode' => '["Online"]',
                'school_id' => '1614169810',
                'branch' => '["Branch Name"]',
                'currency' => 'GBP',
                'program_name' => \Str::random(10),
                'program_level' => 'aaaa',
                'lessons_per_week' => 'aaaaaa',
                'hours_per_week' => 'aa',
                'study_time' => '["Morning"]',
                'every_day' => '["Monday"]',
                'about_program' => 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                'created_at' => '2021-04-12 12:58:55',
                'updated_at' => '2021-04-12 12:58:55',
            ),
            17 =>
            array (
                'unique_id' => '929',
                'language' => '["English"]',
                'program_type' => '["New program"]',
                'study_mode' => '["Online"]',
                'school_id' => '1614169810',
                'branch' => '["Branch Name"]',
                'currency' => 'AUS',
                'program_name' => \Str::random(10),
                'program_level' => NULL,
                'lessons_per_week' => 'Aut hic quis quia ei',
                'hours_per_week' => 'Necessitatibus sint',
                'study_time' => '["Morning"]',
                'every_day' => '["Monday"]',
                'about_program' => 'Tempore rerum eius',
                'created_at' => '2021-04-09 11:02:33',
                'updated_at' => '2021-04-09 11:02:33',
            ),
            18 =>
            array (
                'unique_id' => '995',
                'language' => '"English"',
                'program_type' => '["General English"]',
                'study_mode' => '["Offline"]',
                'school_id' => '176',
                'branch' => '["center"]',
                'currency' => 'USD',
                'program_name' => \Str::random(10),
                'program_level' => 'A1',
                'lessons_per_week' => '30',
                'hours_per_week' => '22.5',
                'study_time' => '["Morning"]',
                'every_day' => '["Monday"]',
                'about_program' => 'test',
                'created_at' => '2021-04-11 20:51:59',
                'updated_at' => '2021-04-11 20:51:59',
            ),
        ));
    }
}
