<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;

class CourseAccomodationsEnTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {       

        \DB::table('course_accommodations_en')->delete();
        
        \DB::table('course_accommodations_en')->insert(array (
            0 => 
            array (
                'unique_id' => '16179461536',
                'course_unique_id' => '660',
                'type' => 'Dolor nulla ipsa ve',
                'room_type' => 'Magna deserunt ut au',
                'meal' => 'Quidem nisi similiqu',
                'age_range' => NULL,
                'placement_fee' => '23',
                'program_duration' => '5',
                'deposit_fee' => '45',
                'custodian_fee' => '54',
                'custodian_age_range' => '["29"]',
                'special_diet_fee' => '34',
                'special_diet_note' => 'At voluptas alias re',
                'fee_per_week' => '34',
                'start_week' => 'Esse nostrum ut tem',
                'end_week' => 'Et eligendi molestia',
                'start_date' => '1992-01-21',
                'end_date' => '2009-04-27',
                'discount_per_week' => 'Non sit reprehender',
                'discount_per_week_symbol' => '%',
                'discount_start_date' => '1987-09-26',
                'discount_end_date' => '1995-09-25',
                'summer_fee_per_week' => 'Laudantium esse co',
                'summer_fee_start_date' => '1975-02-28',
                'summer_fee_end_date' => '1998-09-10',
                'peak_time_fee_per_week' => 'Ea voluptatibus volu',
                'peak_time_fee_start_date' => '1970-01-31',
                'peak_time_fee_end_date' => '1998-03-02',
                'christmas_fee_per_week' => 'Aut elit vel accusa',
                'christmas_fee_start_date' => '2008-03-19',
                'christmas_fee_end_date' => '1983-05-18',
                'created_at' => '2021-04-09 11:00:01',
                'updated_at' => '2021-04-09 11:00:01',
            ),
            1 => 
            array (
                'unique_id' => '16179461537',
                'course_unique_id' => '660',
                'type' => 'Dolor nulla ipsa ve',
                'room_type' => 'Magna deserunt ut au',
                'meal' => 'Quidem nisi similiqu',
                'age_range' => NULL,
                'placement_fee' => '23',
                'program_duration' => '5',
                'deposit_fee' => '45',
                'custodian_fee' => '54',
                'custodian_age_range' => '["29"]',
                'special_diet_fee' => '34',
                'special_diet_note' => 'At voluptas alias re',
                'fee_per_week' => '34',
                'start_week' => 'Esse nostrum ut tem',
                'end_week' => 'Et eligendi molestia',
                'start_date' => '1992-01-21',
                'end_date' => '2009-04-27',
                'discount_per_week' => 'Non sit reprehender',
                'discount_per_week_symbol' => '%',
                'discount_start_date' => '1987-09-26',
                'discount_end_date' => '1995-09-25',
                'summer_fee_per_week' => 'Laudantium esse co',
                'summer_fee_start_date' => '1975-02-28',
                'summer_fee_end_date' => '1998-09-10',
                'peak_time_fee_per_week' => 'Ea voluptatibus volu',
                'peak_time_fee_start_date' => '1970-01-31',
                'peak_time_fee_end_date' => '1998-03-02',
                'christmas_fee_per_week' => 'Aut elit vel accusa',
                'christmas_fee_start_date' => '2008-03-19',
                'christmas_fee_end_date' => '1983-05-18',
                'created_at' => '2021-04-09 11:00:01',
                'updated_at' => '2021-04-09 11:00:01',
            ),
            2 => 
            array (
                'unique_id' => '161794004689',
                'course_unique_id' => '89',
                'type' => 'Officia corrupti au',
                'room_type' => 'Aperiam vel consecte',
                'meal' => 'Quia iusto ea neque',
                'age_range' => NULL,
                'placement_fee' => 'Alias sunt duis dese',
                'program_duration' => 'Dolores aut id ulla',
                'deposit_fee' => 'Et ea esse adipisici',
                'custodian_fee' => 'Vel consectetur eum',
                'custodian_age_range' => '["29"]',
                'special_diet_fee' => 'Ducimus omnis nisi',
                'special_diet_note' => 'Repellendus Facere',
                'fee_per_week' => 'Et iure sint veniam',
                'start_week' => 'Ullam eligendi praes',
                'end_week' => 'Corporis sint tempor',
                'start_date' => '1978-10-11',
                'end_date' => '2006-11-25',
                'discount_per_week' => 'Est fugit mollitia',
                'discount_per_week_symbol' => '%',
                'discount_start_date' => '1988-06-25',
                'discount_end_date' => '1985-04-04',
                'summer_fee_per_week' => 'Est dolor assumenda',
                'summer_fee_start_date' => '2002-12-09',
                'summer_fee_end_date' => '1982-02-08',
                'peak_time_fee_per_week' => 'Voluptatem laboris',
                'peak_time_fee_start_date' => '1979-11-20',
                'peak_time_fee_end_date' => '2002-11-26',
                'christmas_fee_per_week' => 'Autem quo est et off',
                'christmas_fee_start_date' => '1992-07-04',
                'christmas_fee_end_date' => '2019-06-07',
                'created_at' => '2021-04-08 23:47:42',
                'updated_at' => '2021-04-08 23:47:42',
            ),
            3 => 
            array (
                'unique_id' => '161794637974',
                'course_unique_id' => '929',
                'type' => 'Et voluptatem Delen',
                'room_type' => 'Et elit distinctio',
                'meal' => 'Iste sit irure quia',
                'age_range' => NULL,
                'placement_fee' => 'Veniam dignissimos',
                'program_duration' => 'Accusantium qui dele',
                'deposit_fee' => 'Quam ut in elit des',
                'custodian_fee' => 'Excepturi nostrum qu',
                'custodian_age_range' => '["29"]',
                'special_diet_fee' => 'Nam et qui enim dolo',
                'special_diet_note' => 'Illo expedita do obc',
                'fee_per_week' => 'Est ut quia atque ra',
                'start_week' => 'Do ipsa facere quia',
                'end_week' => 'Libero numquam cumqu',
                'start_date' => '2014-07-03',
                'end_date' => '1999-03-10',
                'discount_per_week' => 'Beatae est dignissim',
                'discount_per_week_symbol' => '%',
                'discount_start_date' => '2000-10-26',
                'discount_end_date' => '1974-01-18',
                'summer_fee_per_week' => 'Quidem repudiandae c',
                'summer_fee_start_date' => '1999-07-15',
                'summer_fee_end_date' => '1987-10-12',
                'peak_time_fee_per_week' => 'Et modi officia ad a',
                'peak_time_fee_start_date' => '1982-02-06',
                'peak_time_fee_end_date' => '2005-07-25',
                'christmas_fee_per_week' => 'Tempora repudiandae',
                'christmas_fee_start_date' => '1982-08-11',
                'christmas_fee_end_date' => '1987-04-10',
                'created_at' => '2021-04-09 11:03:18',
                'updated_at' => '2021-04-09 11:03:18',
            ),
            4 => 
            array (
                'unique_id' => '161794637975',
                'course_unique_id' => '929',
                'type' => 'Et voluptatem Delen',
                'room_type' => 'Et elit distinctio',
                'meal' => 'Iste sit irure quia',
                'age_range' => NULL,
                'placement_fee' => 'Veniam dignissimos',
                'program_duration' => 'Accusantium qui dele',
                'deposit_fee' => 'Quam ut in elit des',
                'custodian_fee' => 'Excepturi nostrum qu',
                'custodian_age_range' => '["29"]',
                'special_diet_fee' => 'Nam et qui enim dolo',
                'special_diet_note' => 'Illo expedita do obc',
                'fee_per_week' => 'Est ut quia atque ra',
                'start_week' => 'Do ipsa facere quia',
                'end_week' => 'Libero numquam cumqu',
                'start_date' => '2014-07-03',
                'end_date' => '1999-03-10',
                'discount_per_week' => 'Beatae est dignissim',
                'discount_per_week_symbol' => '%',
                'discount_start_date' => '2000-10-26',
                'discount_end_date' => '1974-01-18',
                'summer_fee_per_week' => 'Quidem repudiandae c',
                'summer_fee_start_date' => '1999-07-15',
                'summer_fee_end_date' => '1987-10-12',
                'peak_time_fee_per_week' => 'Et modi officia ad a',
                'peak_time_fee_start_date' => '1982-02-06',
                'peak_time_fee_end_date' => '2005-07-25',
                'christmas_fee_per_week' => 'Tempora repudiandae',
                'christmas_fee_start_date' => '1982-08-11',
                'christmas_fee_end_date' => '1987-04-10',
                'created_at' => '2021-04-09 11:03:18',
                'updated_at' => '2021-04-09 11:03:18',
            ),
            5 => 
            array (
                'unique_id' => '161815352233',
                'course_unique_id' => '340',
                'type' => 'Accom type',
                'room_type' => 'room type',
                'meal' => 'meal',
                'age_range' => '["17","19"]',
                'placement_fee' => '200',
                'program_duration' => '5',
                'deposit_fee' => '100',
                'custodian_fee' => '200',
                'custodian_age_range' => '["17","18","29","18"]',
                'special_diet_fee' => '100',
                'special_diet_note' => 'note on dit',
                'fee_per_week' => '100',
                'start_week' => '1',
                'end_week' => '10',
                'start_date' => '2021-04-01',
                'end_date' => '2021-05-01',
                'discount_per_week' => '10 %',
                'discount_per_week_symbol' => NULL,
                'discount_start_date' => '2021-04-01',
                'discount_end_date' => '2021-05-01',
                'summer_fee_per_week' => '100',
                'summer_fee_start_date' => '2021-04-01',
                'summer_fee_end_date' => '2021-05-01',
                'peak_time_fee_per_week' => '200',
                'peak_time_fee_start_date' => '2021-04-01',
                'peak_time_fee_end_date' => '2021-04-01',
                'christmas_fee_per_week' => '100',
                'christmas_fee_start_date' => '2021-12-01',
                'christmas_fee_end_date' => '2021-12-30',
                'created_at' => '2021-04-11 20:43:41',
                'updated_at' => '2021-04-11 20:43:41',
            ),
            6 => 
            array (
                'unique_id' => '161815352234',
                'course_unique_id' => '340',
                'type' => 'Accom type',
                'room_type' => 'room type',
                'meal' => 'meal',
                'age_range' => '["17","19"]',
                'placement_fee' => '200',
                'program_duration' => '5',
                'deposit_fee' => '100',
                'custodian_fee' => '200',
                'custodian_age_range' => '["17","18","29","18"]',
                'special_diet_fee' => '100',
                'special_diet_note' => 'note on dit',
                'fee_per_week' => '100',
                'start_week' => '11',
                'end_week' => '20',
                'start_date' => '2021-04-01',
                'end_date' => '2021-05-01',
                'discount_per_week' => '10 %',
                'discount_per_week_symbol' => NULL,
                'discount_start_date' => '2021-04-01',
                'discount_end_date' => '2021-05-01',
                'summer_fee_per_week' => '100',
                'summer_fee_start_date' => '2021-04-01',
                'summer_fee_end_date' => '2021-05-01',
                'peak_time_fee_per_week' => '200',
                'peak_time_fee_start_date' => '2021-04-01',
                'peak_time_fee_end_date' => '2021-04-01',
                'christmas_fee_per_week' => '100',
                'christmas_fee_start_date' => '2021-12-01',
                'christmas_fee_end_date' => '2021-12-30',
                'created_at' => '2021-04-11 20:43:41',
                'updated_at' => '2021-04-11 20:43:41',
            ),
            7 => 
            array (
                'unique_id' => '161815352235',
                'course_unique_id' => '340',
                'type' => 'Accom type',
                'room_type' => 'room type',
                'meal' => 'meal',
                'age_range' => '["17","19"]',
                'placement_fee' => '200',
                'program_duration' => '5',
                'deposit_fee' => '100',
                'custodian_fee' => '200',
                'custodian_age_range' => '["17","18","29","18"]',
                'special_diet_fee' => '100',
                'special_diet_note' => 'note on dit',
                'fee_per_week' => '100',
                'start_week' => '11',
                'end_week' => '20',
                'start_date' => '2021-04-01',
                'end_date' => '2021-05-01',
                'discount_per_week' => '10 %',
                'discount_per_week_symbol' => NULL,
                'discount_start_date' => '2021-04-01',
                'discount_end_date' => '2021-05-01',
                'summer_fee_per_week' => '100',
                'summer_fee_start_date' => '2021-04-01',
                'summer_fee_end_date' => '2021-05-01',
                'peak_time_fee_per_week' => '200',
                'peak_time_fee_start_date' => '2021-04-01',
                'peak_time_fee_end_date' => '2021-04-01',
                'christmas_fee_per_week' => '100',
                'christmas_fee_start_date' => '2021-12-01',
                'christmas_fee_end_date' => '2021-12-30',
                'created_at' => '2021-04-11 20:43:41',
                'updated_at' => '2021-04-11 20:43:41',
            ),
            8 => 
            array (
                'unique_id' => '161821230690',
                'course_unique_id' => '627',
                'type' => 'Homestay',
                'room_type' => 'Single',
                'meal' => '2meal',
                'age_range' => '["23","25","26","14","15","16","17","18","19","20","21","22","23","25","26","28","35","14","15","16","17","18","19","20","21"]',
                'placement_fee' => '200',
                'program_duration' => '10',
                'deposit_fee' => '100',
                'custodian_fee' => '100',
                'custodian_age_range' => '["16","17","15"]',
                'special_diet_fee' => '10',
                'special_diet_note' => 'tttttt',
                'fee_per_week' => '300',
                'start_week' => '1',
                'end_week' => '48',
                'start_date' => '2021-01-01',
                'end_date' => '2021-12-31',
                'discount_per_week' => '10 %',
                'discount_per_week_symbol' => NULL,
                'discount_start_date' => '2021-01-01',
                'discount_end_date' => '2021-06-30',
                'summer_fee_per_week' => '10',
                'summer_fee_start_date' => '2021-05-03',
                'summer_fee_end_date' => '2021-05-24',
                'peak_time_fee_per_week' => '10',
                'peak_time_fee_start_date' => '2021-05-03',
                'peak_time_fee_end_date' => '2021-05-24',
                'christmas_fee_per_week' => '10',
                'christmas_fee_start_date' => '2021-05-17',
                'christmas_fee_end_date' => '2021-05-31',
                'created_at' => '2021-04-12 13:00:24',
                'updated_at' => '2021-04-12 13:00:24',
            ),
            9 => 
            array (
                'unique_id' => '161821230691',
                'course_unique_id' => '627',
                'type' => 'Homestay',
                'room_type' => 'Single',
                'meal' => 'no meal',
                'age_range' => '["23","25","26","14","15","16","17","18","19","20","21","22","23","25","26","28","35","14","15","16","17","18","19","20","21"]',
                'placement_fee' => '200',
                'program_duration' => '10',
                'deposit_fee' => '100',
                'custodian_fee' => '100',
                'custodian_age_range' => '["16","17","15"]',
                'special_diet_fee' => '10',
                'special_diet_note' => 'tttttt',
                'fee_per_week' => '200',
                'start_week' => '1',
                'end_week' => '48',
                'start_date' => '2021-01-01',
                'end_date' => '2021-12-31',
                'discount_per_week' => '10 %',
                'discount_per_week_symbol' => NULL,
                'discount_start_date' => '2021-01-01',
                'discount_end_date' => '2021-06-30',
                'summer_fee_per_week' => '10',
                'summer_fee_start_date' => '2021-05-03',
                'summer_fee_end_date' => '2021-05-24',
                'peak_time_fee_per_week' => '10',
                'peak_time_fee_start_date' => '2021-05-03',
                'peak_time_fee_end_date' => '2021-05-24',
                'christmas_fee_per_week' => '10',
                'christmas_fee_start_date' => '2021-05-17',
                'christmas_fee_end_date' => '2021-05-31',
                'created_at' => '2021-04-12 13:00:24',
                'updated_at' => '2021-04-12 13:00:24',
            ),
        ));
    }
}